config/routes.rb
Rails.application.routes.draw do
  resources :clients
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  resources :users
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :account_activations, only: [:edit]
  resources :microposts,          only: [:create, :destroy]
  resources :clients
  
  
end

app/models/client.rb
class Client < ApplicationRecord
  before_save { self.client_identifier = client_identifier.upcase }
  
  
  validates :name, presence: true, length: { maximum: 50 }
  validates :client_identifier, presence: true, length:  { in: 4..20 },   # "in" stands for "inclusive" not "inbetween"--- min valid length is 4 and maximum valid is 20
                                                uniqueness: { case_sensitive: false }
                                                
  VALID_ZIP_REGEX =  /(^\d{5}(?:[\s]?[-\s][\s]?\d{4})?$)/
  validates :zip, :allow_blank => true, length: { in: 5..10 },  format: { with: VALID_ZIP_REGEX  }
  



end #end of class

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
       format.html { redirect_to @client }  #alternative with notice below
#       format.html { redirect_to @client, notice: 'Client was successfully created.'}
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client }   #alternative with notice commented out below
#       format.html { redirect_to @client, notice: 'Client was successfully updated.'}
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url }  # Alternative with notice commented out below
#      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :client_identifier, :primary_contact, :address_line_two, :city, :zip, :state)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<h2><%= yield(:title) %></h2>
 
<%= simple_form_for (@client) do |f| %>

<div class="form-card">
<div  class="form-inline form client_form">
    <div class="form-group client_group">
  <%= f.input :name, label: 'Name*'%>
  <%= f.input :client_identifier, label: 'Client identifier*'%> 
    </div> 
</div> 
<hr> </hr>

<div class="group-header">Address</div>
<div class="form-inline form client_form">
  <div class="form-group client_group">
  <%= f.input :address_line_two, label: 'Street#1' %>
  </div>
</div>

<div class="form-inline form client_form">
  <div class="form-group client_group">
  <%= f.input :addressthree, label: 'Street#2' %>
  </div>
</div>


<div class="form-inline form client_form">
 <div class="form-group client_group">
<%= f.input :city, label: 'City'%>
 <%= f.input :state, label: 'State',
collection: ['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL',
              'GA', 'HI', 'ID', 'IL', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD',
              'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 
              'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI','SC',
              'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY'  ]   %>
<%= f.input :zip, label: 'Zip'   %>
  </div>
</div>


<hr> </hr>

<div class="group-header">Primary Contact</div>
<div  class="form-inline form client_form">
    <div class="form-group client_group">
  <%= f.input :first_name, label: 'First name'%>
  <%= f.input :last_name, label: 'Last name'%>
  <%= f.input :contactphone, label: 'Phone No.'%> 
    </div> 
</div> 


<div class="client_button_wrapper">
<%= f.button :submit %>
</div>

</div>


<% end %> 

app/views/clients/edit.html.erb
<% provide(:title, "Editing Client") %>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Client identifier</th>
      <th>Primary contact</th>
      <th>Street Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td><%= client.client_identifier %></td>
        <td><%= client.primary_contact %></td>
        <td><%= client.address_line_two %></td>
        <td><%= client.city %></td>
        <td><%= client.state %></td>
        <td><%= client.zip %></td>

        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<% provide(:title, "New Client") %>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Client identifier:</strong>
  <%= @client.client_identifier %>
</p>

<p>
  <strong>Street address:</strong>
  <%= @client.address_line_two %>
</p>

<p>
  <strong>City:</strong>
  <%= @client.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @client.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @client.zip %>
</p>

<p>
  <strong>Primary contact:</strong>
  <%= @client.primary_contact %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>