config/routes.rb
Rails.application.routes.draw do
  resources :clients
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  resources :users
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :account_activations, only: [:edit]
  resources :microposts,          only: [:create, :destroy]
  resources :clients
  
  
end

app/views/layouts/_appnav.html.erb
<% if logged_in? %>   <!-- Only show navbar if logged in -->

<header>
<!-- Below is the Gimlet/bootstrap navbar changed for our purposes -->
  <div class="appnav"> 
  <nav class="navbar navbar-default" role="navigation" id="appnav" >

  <div class="container" >
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- <a class="navbar-brand" href="#">Brand</a>         -->
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!--  <li class="active"><a href="#">Link</a></li>   -->
       <!--  <li><a href="#">Link</a></li>  -->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Clients<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="/clients">Client List</a> </li>
            <li><a href="/clients/new">Create Client</a></li>
        <!-- <li><a href="#">Something else here</a></li>   
            <li class="divider"></li>
           <li><a href="#">Separated link</a></li>  
            <li class="divider"></li>
         <!--   <li><a href="#">One more separated link</a></li> -->
          </ul>
        </li>
      </ul>
      <!-- <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>  -->
      <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Utilities <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
             <li><%= link_to "Users", users_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
          <!--   <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>   -->
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>
</div>  <!-- /.appnav -->
<!-- end of the Gimlet/bootstrap navbar -->
<% else %>
<% end %>

</header>

app/views/layouts/_base.html.erb
<!DOCTYPE html>
<%= html_tag :lang => "en" do %>
  <head>
    <meta charset="utf-8">
    <title><%= [@title, app_name].compact.join(" - ") %></title>
    <%= csrf_meta_tags %>
    
    <!-- Ensure devices display responsive pages properly -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le fonts -->
    <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Droid+Sans:400,700" %>

    <!-- Le styles -->
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= yield :styles %>

    <!-- Le fav and touch icons -->
    <%= favicon_link_tag %>
    <%# favicon_link_tag "apple-touch-icon.png", :rel => "apple-touch-icon" %>
    
    <%= yield :head %>
  </head>
  <body>

    <header>
      <%= render "layouts/navbar" %>
      <%= yield :header %>
    </header>
    <%= yield :banner %>
   <%= render "layouts/appnav"%>
    <div id="main">
      <div class="container">
        <%= render "layouts/flashes" %>
        <%= yield %>
      </div> <!-- /.container -->
    </div> <!-- /#main -->
 
  <%= render "layouts/footer" %>
 
    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <%= yield :javascript %>
    
  </body>
<% end %>

app/views/layouts/_defaultheader.html.erb
    <%= stylesheet_link_tag    'application', media: 'all',
                                            #  'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_flashes.html.erb
<% if alert %>
  <div class="alert alert-danger">
    <a class="close" data-dismiss="alert">&times;</a>
    <%= icon_tag "remove" %> <%= alert %>
  </div>
<% end %>

<% if notice %>
  <div class="alert alert-warning">
    <a class="close" data-dismiss="alert">&times;</a>
    <%= icon_tag "info-sign" %> <%= notice %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <p class="pull-right">
      <%= link_to "Home", root_path %>
      &middot;
      <%= link_to "About", "#" %>
      &middot;
      <%= link_to "Contact Us", "#" %>
      &middot;
      <%= link_to "Terms", "#" %>
      &middot;
      <%= link_to "Privacy", "#" %>
    </p>
    <p>&copy; <%= Date.today.year %> <%= app_name %>. All rights reserved.</p>

  </div> <!-- /.container -->
</footer>

app/views/layouts/_form.html.erb
 <%= form_for(@user, url: yield(:originatingurl)) do |f| %>
 <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/layouts/_header.html.erb
<% if logged_in? %>

<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

<% else %>

<% end %>

app/views/layouts/_navbar.html.erb
<%# Top navigation bar containing the main menu of your app. %>
<nav class="navbar navbar-default navbar-inverse">
  <!-- TIP: to unfix the navbar:
    1. remove the 'navbar-fixed-top' class here and
    2. add the 'static-navbar' class to your body tag. -->
  <div class="navbar-inner">
    <div class="container">

      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#"></a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
      <!--    <%= activatable_li_tag_with_link "Home", root_path %>  -->
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <%= yield :navbar %>
        </ul>

    </div> <!-- /.container -->
  </div> <!-- /.navbar-inner -->
</nav> <!-- /.navbar -->

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_user_nav.html.erb
<%# Links for current user. %>

<%
=begin %>
<div class="navbar-text pull-right">
<%= icon_tag "user" %> Welcome, <strong><%= "User" %></strong>
<span class="divider">|</span>
<%= link_to "Settings", "#" %>

</div>
<%
=end %>

app/views/layouts/application.html.erb
<% content_for :navbar,  render("layouts/user_nav")   %>

<%=  render :layout => "layouts/base" do %>
  <div class="page-header">
    <div class="row">
      <div class="col-md-12">

<%
=begin %>
        <%= yield(:title)  %>
        <%= yield :description %>
<%
=end %>

      </div>
      <div class="col-md-12">
      
        <%= yield :actions %>
      </div>
    </div>
  </div><!-- /.page-header -->

  <div class="row">
    <div id="content" class="col-md-12">
      <%= yield  %>
    </div> <!-- /#content -->
  </div> <!-- /.row -->

<% end %> <!-- end of render do -->

app/views/layouts/home.html.erb
<% content_for :navbar do %>
  <li>
    <%= form_tag "?", :class => "navbar-form hidden-sm navbar-search", role:'search' do %>
      <%= text_field_tag :query, params[:query], :class => "search-query" %>
    <% end %>
  </li>
<% end %>

<%= render :layout => "layouts/base" do %>
  <%= yield %>
<% end %>

app/views/layouts/sessions.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
  <%= yield %>
  </body>
</html>